Repository faker-ruby/faker, pull requests merged in 2018-07, with the labels that each got.

#1004 Add Faker::Ethereum
  CHANGELOG.md
  README.md
  doc/ethereum.md
  lib/faker/ethereum.rb
  test/test_faker_ethereum.rb
Labels: Feature Request, Waiting for author's response

#1300 Add Faker::GreekPhilosophers
  CHANGELOG.md
  README.md
  doc/greek_philosophers.md
  lib/faker/greek_philosophers.rb
  lib/locales/en/greek_philosophers.yml
  test/test_faker_greek_philosophers.rb
Labels: Feature Request

#1299 Add Faker::Bank - account_number and routing_number
  .rubocop.yml
  CHANGELOG.md
  doc/bank.md
  lib/faker/bank.rb
  test/test_determinism.rb
  test/test_ee_locale.rb
  test/test_faker_bank.rb
Labels: Feature Request

#1305 Fix YAML syntax - single quote escape ( on vehicle.yml )
  lib/locales/en/vehicle.yml
Labels: Bug/Fixes

#1308 Bojack Horseman
  doc/bojack_horseman.md
  lib/faker/bojack_horseman.rb
  lib/locales/en/bojack_horseman.yml
  test/test_faker_bojack_horseman.rb
Labels: Feature Request

#1196 Fix PhoneNumber in es-MX
  CHANGELOG.md
  lib/faker.rb
  test/test_es_mx_locale.rb
  test/test_faker.rb
Labels: Bug/Fixes

#1304 Fix Faker::Source ruby language examples
  lib/locales/en/source.yml
  test/test_faker_source.rb
Labels: Chores

#801 Add Faker::NHS - Support for the British National Health Service
  CHANGELOG.md
  README.md
  doc/national_health_service.md
  lib/faker/nhs.rb
  test/test_faker_national_health_service.rb
Labels: Feature Request

#527 Fix time period test that could result in a flake test within 15 days…
  test/test_faker_time.rb
Labels: Bug/Fixes

#1310 Add alias for middle_name and remove locale
  CHANGELOG.md
  CONTRIBUTING.md
  lib/faker/name.rb
  lib/locales/en/name.yml
Labels: Bug/Fixes

#1115 Add Faker::Cosmere
  README.md
  doc/cosmere.md
  lib/faker/cosmere.rb
  lib/locales/en/cosmere.yml
  test/test_faker_cosmere.rb
Labels: Feature Request

#372 Add test_password_could_achieve_max_length
  test/test_faker_internet.rb
Labels: Bug/Fixes

#1307 Add Faker::UniqueGenerator - exclude method
  README.md
  lib/helpers/unique_generator.rb
  test/test_faker_lorem.rb
Labels: Feature Request

#1313 Add Faker::Restaurant
  README.md
  doc/restaurant.md
  lib/faker/restaurant.rb
  lib/locales/en/restaurant.yml
  test/test_faker_restaurant.rb
Labels: Feature Request

#1314 Add Faker::SouthPark
  CHANGELOG.md
  README.md
  doc/south_park.md
  lib/faker/south_park.rb
  lib/locales/en/south_park.yml
  test/test_faker_south_park.rb
Labels: Feature Request

#1246 Store list of generators with enabled uniqueness for faster clear
  CHANGELOG.md
  lib/helpers/unique_generator.rb
Labels: Suggestion

#893 Add Faker::ChileRut
  CHANGELOG.md
  README.md
  doc/chile_rut.md
  lib/faker/chile_rut.rb
  test/test_determinism.rb
  test/test_faker_chile_rut.rb
Labels: Feature Request

#1148 Adding Industry Segments Class
  README.md
  doc/industry_segments.md
  lib/faker/industry_segments.rb
  lib/locales/en/industry_segments.yml
  test/test_faker_industry_segments.rb
Labels: Feature Request, Waiting for author's response

#1320 Add Faker::Buffy
  README.md
  doc/buffy.md
  lib/faker/buffy.rb
  lib/locales/en/buffy.yml
  test/test_faker_buffy.rb
Labels: Feature Request

#1319 Added Faker::DC Comics
  README.md
  doc/dc_comics.md
  lib/faker/dc_comics.rb
  lib/locales/en/dc_comics.yml
  test/test_faker_dc_comics.rb
Labels: Feature Request
