Repository faker-ruby/faker, pull requests merged in 2018-05, with the labels that each got.

#1122 Fix formatting for Brazilian phone and cell phone numbers
  lib/locales/pt-BR.yml
Labels: Bug/Fixes

#1124 Fix ranges for Brazilian zip codes
  lib/locales/pt-BR.yml
Labels: Bug/Fixes

#1202 adds both inclusive and binary gender option
  README.md
  doc/gender.md
  lib/faker/gender.rb
  lib/locales/en/gender.yml
  test/test_faker_gender.rb
Labels: Feature Request

#1189 Add Faker::Football
  README.md
  doc/football.md
  lib/faker/football.rb
  lib/locales/en/football.yml
  test/test_faker_football.rb
Labels: Feature Request

#1136 Modify Faker::Internet.slug
  lib/faker/internet.rb
  test/test_faker_internet.rb
Labels: Bug/Fixes

#1207 use default rake task
  .travis.yml
  lib/faker/internet.rb
Labels: Bug/Fixes

#1147 Add Spanish citizen id and docs
  .rubocop.yml
  README.md
  doc/id_number.md
  lib/faker/id_number.rb
  test/test_faker_id_number.rb
Labels: Documentation, Feature Request

#1210 Features/add coveralls
  .coveralls.yml
  .gitignore
  Gemfile.lock
  README.md
  faker.gemspec
  test/test_helper.rb
Labels: Feature Request

#1181 Fix: Moved the Google Omniauth key id_info from root into extra
  lib/faker/omniauth.rb
  test/test_faker_omniauth.rb
Labels: Bug/Fixes

#1209 Add Faker::Source
  CHANGELOG.md
  README.md
  doc/source.md
  lib/faker/source.rb
  lib/locales/en/source.yml
  test/test_faker_source.rb
Labels: Feature Request

#1212 Coveralls should ignore test folder
  .coveralls.yml
  .gitignore
  Gemfile.lock
  faker.gemspec
  test/test_faker_omniauth.rb
  test/test_helper.rb
Labels: Bug/Fixes, WIP

#1215 Added Nato Phonetic Alphabet
  CHANGELOG.md
  README.md
  doc/nato_phonetic_alphabet.md
  lib/faker/nato_phonetic_alphabet.rb
  lib/locales/en/nato_phonetic_alphabet.yml
  test/test_nato_phonetic_alphabet.rb
Labels: Feature Request

#1213 Add missing tests after adding Coveralls
  doc/measurement.md
  lib/faker/internet.rb
  lib/faker/measurement.rb
  lib/faker/phone_number.rb
  test/test_faker_demographic.rb
  test/test_faker_internet.rb
  test/test_faker_measurement.rb
  test/test_faker_stripe.rb
  test/test_helper.rb
Labels: Bug/Fixes, Suggestion

#1142 Missing i18n jobs fix
  lib/faker/job.rb
  test/test_faker_job.rb
  test/test_faker_job_locale.rb
Labels: Bug/Fixes

#1135 Added documentation for dumb and dumber
  README.md
  doc/dumb_and_dumber.md
  lib/locales/en/dumb_and_dumber.yml
Labels: Documentation

#1198 Rename methods on Faker::Types to avoid shadowing ruby standard methods
  doc/types.md
  lib/faker/types.rb
  test/test_faker_types.rb
Labels: Refactoring

#1211 adds bands, albums, and genres to music
  CHANGELOG.md
  doc/music.md
  lib/faker/music.rb
  lib/locales/en/music.yml
  test/test_faker_music.rb
Labels: Feature Request

#1192 Space: Added space launch vehicule
  CHANGELOG.md
  doc/space.md
  lib/faker/space.rb
  lib/locales/en/space.yml
  test/test_faker_space.rb
Labels: Feature Request

#818 LoremFlickr support
  CHANGELOG.md
  README.md
  doc/lorem_flickr.md
  lib/faker/lorem_flickr.rb
  test/test_faker_lorem_flickr.rb
Labels: Feature Request

#1218 Add Faker::Myst
  lib/faker/myst.rb
  lib/locales/en/myst.yml
  test/test_faker_myst.rb
Labels: Feature Request

#1128 Use ruby syntax highlighting in Omniauth doc
  doc/omniauth.md
Labels: Documentation

#1179 Random color with Placeholdit
  CHANGELOG.md
  doc/placeholdit.md
  lib/faker/placeholdit.rb
  test/test_placeholdit.rb
Labels: Feature Request, Suggestion

#439 Remove Eichmann surname
  lib/locales/de-AT.yml
  lib/locales/de.yml
  lib/locales/en/name.yml
Labels: Documentation

#974 [docs] Specify version number each class was introduced
  doc/address.md
  doc/ancient.md
  doc/app.md
  doc/beer.md
  doc/boolean.md
  doc/cat.md
  doc/chuck_norris.md
  doc/compass.md
  doc/crypto.md
  doc/demographic.md
  doc/dessert.md
  doc/dragon_ball.md
  doc/educator.md
  doc/file.md
  doc/fillmurray.md
  doc/food.md
  doc/friends.md
  doc/funny_name.md
  doc/game_of_thrones.md
  doc/harry_potter.md
  doc/hey_arnold.md
  doc/hitchhikers_guide_to_the_galaxy.md
  doc/hobbit.md
  doc/how_i_met_your_mother.md
  doc/league_of_legends.md
  doc/lorem_pixel.md
  doc/markdown.md
  doc/matz.md
  doc/music.md
  doc/omniauth.md
  doc/overwatch.md
  doc/pokemon.md
  doc/rick_and_morty.md
  doc/robin.md
  doc/rupaul.md
  doc/simpsons.md
  doc/slack_emoji.md
  doc/space.md
  doc/star_trek.md
  doc/star_wars.md
  doc/superhero.md
  doc/twin_peaks.md
  doc/twitter.md
  doc/university.md
  doc/vehicle.md
  doc/zelda.md
Labels: Documentation

#1174 [ADD] Dota2: Str Heroes, heroes quotes, Items, Teams, Players
  lib/faker/dota.rb
  lib/locales/en/dota.yml
  test/test_faker_dota.rb
Labels: Feature Request

#1108 Update Faker::Dessert
  lib/locales/en/dessert.yml
Labels: Update locales

#1134 Test against latest Ruby versions
  .travis.yml
Labels: Feature Request

#1225 Test against latest Ruby versions
  .travis.yml
Labels: Suggestion

#1227 Update RuboCop to 0.56.0
  Gemfile.lock
  lib/faker/star_wars.rb
  lib/helpers/unique_generator.rb
Labels: Bug/Fixes

#1228 Added Japanese color to yml
  lib/locales/ja.yml
Labels: Update locales

#1229 sv.yml: Typos
  lib/locales/sv.yml
Labels: Update locales

#792 Add Faker for Famous Last Words
  CHANGELOG.md
  doc/famous_last_words.md
  lib/faker/famous_last_words.rb
  lib/locales/en/famous_last_words.yml
  lib/locales/en/job.yml
  test/test_faker_famous_last_words.rb
Labels: Feature Request

#1205 Show the type of field that violated a uniqueness constraint
  lib/helpers/unique_generator.rb
  test/test_faker_unique_generator.rb
Labels: Bug/Fixes, Suggestion

#246 latitude and longitude should be float instead of string.
  lib/faker/address.rb
Labels: Bug/Fixes, Suggestion

#1232 Fix file permissions
  lib/faker/time.rb
  test/test_faker_time.rb
Labels: Suggestion

#1144 Added polish_register_of_national_economy and polish_taxpayer_identification_number
  doc/company.md
  lib/faker/company.rb
  test/test_faker_company.rb
Labels: Feature Request

#1129 Added SingularSiegler quotes
  README.md
  doc/singular_siegler.md
  lib/faker/singular_siegler.rb
  lib/locales/en/singular_siegler.yml
  test/test_faker_singular_siegler.rb
Labels: Feature Request

#1235 Added Faker::Community
  .bundle/config
  CHANGELOG.md
  README.md
  doc/community.md
  lib/faker/community.rb
  lib/locales/en/community.yml
  test/test_faker_community.rb
Labels: Feature Request

#1199 Add Faker::StrangerThings
  CHANGELOG.md
  Gemfile.lock
  README.md
  doc/stranger_thing.md
  lib/faker/stranger_thing.rb
  lib/locales/en/stranger_thing.yml
  test/test_stranger_thing.rb
Labels: Feature Request

#1236 Updates dessert faker
  doc/dessert.md
  lib/locales/en.yml
  lib/locales/en/dessert.yml
  test/test_faker_dessert.rb
Labels: Feature Request, Update locales

#1146 Update company docs
  doc/company.md
Labels: Documentation

#987 Add Faker::Cannabis class
  CHANGELOG.md
  README.md
  doc/cannabis.md
  lib/faker/cannabis.rb
  lib/locales/en/cannabis.yml
  test/test_faker_cannabis.rb
Labels: Feature Request

#900 Add Japanese lorem words to locale
  lib/faker/lorem.rb
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Feature Request

#1109 Added Princess Bride
  README.md
  doc/princess_bride.md
  lib/faker/princess_bride.rb
  lib/locales/en/princess_bride.yml
  test/test_faker_princess_bride.rb
Labels: Feature Request

#1239 Updates Food Faker to separate out Fruits and Veggies
  CHANGELOG.md
  doc/food.md
  lib/faker/food.rb
  lib/locales/en/food.yml
  test/test_faker_food.rb
Labels: Feature Request

#1240 Add some tests
  test/test_faker_company.rb
  test/test_faker_measurement.rb
  test/test_faker_types.rb
Labels: Bug/Fixes

#1106 Adds turkish phone number formats and test.
  CHANGELOG.md
  lib/locales/tr.yml
  test/test_tr_locale.rb
Labels: Feature Request

#1248 Remove duplications from company.md
  doc/company.md
Labels: Documentation

#1247 Generate capital city of random Nation
  doc/nation.md
  lib/faker/nation.rb
  lib/locales/en/nation.yml
  test/test_faker_nation.rb
Labels: Feature Request

#1249 Update list of name prefixes for sv locale
  lib/locales/sv.yml
  test/test_sv_locale.rb
Labels: Update locales

#1254 Added missing documentation for Code faker. Fixes #1251
  doc/code.md
Labels: Documentation

#1252 Add missing documentation - Faker::Address to Faker::Myst
  README.md
  doc/address.md
  doc/aqua_teen_hunger_force.md
  doc/artist.md
  doc/bitcoin.md
  doc/bossa_nova.md
  doc/breaking_bad.md
  doc/commerce.md
  doc/community.md
  doc/currency.md
  doc/dota.md
  doc/dune.md
  doc/esport.md
  doc/finance.md
  doc/food.md
  doc/game_of_thrones.md
  doc/gender.md
  doc/hey_arnold.md
  doc/internet.md
  doc/kpop.md
  doc/lebowski.md
  doc/lorem.md
  doc/measurement.md
  lib/faker/company.rb
  lib/locales/en/lord_of_the_rings.yml
  test/test_faker_company.rb
Labels: Documentation

#1256 Fixing documentation - Faker::Name to Faker::Zelda
  doc/name.md
  doc/nation.md
  doc/nato_phonetic_alphabet.md
  doc/number.md
  doc/star_wars.md
  doc/university.md
  lib/faker/team.rb
Labels: Documentation

#1258 Remove simplecov-console and add coverage_report rake task
  CHANGELOG.md
  CONTRIBUTING.md
  Gemfile.lock
  Rakefile
  faker.gemspec
  test/test_helper.rb
Labels: Feature Request

#1241 Add missing tests reported by SimpleCov
  CHANGELOG.md
  lib/faker/types.rb
  test/test_faker_char.rb
  test/test_faker_unique_generator.rb
  test/test_helper.rb
  test/test_ru_locale.rb
  test/test_uk_locale.rb
Labels: Bug/Fixes

#1140 Add Estonian and Latvian locales
  CHANGELOG.md
  lib/locales/ee.yml
  lib/locales/en/lorem.yml
  lib/locales/lv.yml
  test/test_ee_locale.rb
  test/test_lv_locale.rb
Labels: Update locales

#1107 Add tokens to Faker::Stripe
  CHANGELOG.md
  doc/stripe.md
  lib/faker/stripe.rb
  lib/locales/en/stripe.yml
  test/test_faker_stripe.rb
Labels: Feature Request

#1222 Add paragraph_by_chars functionality
  CHANGELOG.md
  doc/hipster.md
  doc/lorem.md
  doc/lovecraft.md
  lib/faker/hipster.rb
  lib/faker/lorem.rb
  lib/faker/lovecraft.rb
  test/test_ee_locale.rb
  test/test_faker_hipster.rb
  test/test_faker_lorem.rb
  test/test_faker_lovecraft.rb
Labels: Feature Request

#1064 Add Faker::Markdown.sandwich
  CHANGELOG.md
  doc/markdown.md
  lib/faker/markdown.rb
  test/test_faker_markdown.rb
Labels: Feature Request

#1259 Modify email method in Internet class
  CHANGELOG.md
  doc/internet.md
  lib/faker/internet.rb
  test/test_faker_internet.rb
Labels: Feature Request
