Repository faker-ruby/faker, pull requests merged in 2018-12, with the labels that each got.

#1488 Fix unreleased docs
  doc/unreleased/blockchain/bitcoin.md
  doc/unreleased/blockchain/ethereum.md
  doc/unreleased/blockchain/tezos.md
  doc/unreleased/tv_shows/silicon_valley.md
Labels: Documentation

#1487 Add Faker::TvShows::TheExpanse
  doc/unreleased/tv_shows/the_expanse.md
  lib/faker/tv_shows/the_expanse.rb
  lib/locales/en/the_expanse.yml
  test/faker/tv_shows/test_the_expanse.rb
  unreleased_README.md
Labels: Feature Request

#1489 Add support to formatted brazilian_citizen_number and brazilian_company_number
  .rubocop.yml
  doc/unreleased/default/company.md
  doc/unreleased/default/id_number.md
  lib/faker/default/company.rb
  lib/faker/default/id_number.rb
  test/faker/default/test_faker_company.rb
  test/faker/default/test_faker_id_number.rb
Labels: Feature Request

#1490 Add missing Faker::HeroesOfTheStorm tests
  CHANGELOG.md
  test/deprecate/test_deprecate_heroes_of_the_storm.rb
Labels: Chores

#1477 Fixed bank account length
  lib/faker/default/bank.rb
  test/faker/default/test_faker_bank.rb
Labels: Bug/Fixes

#1494 Fix Faker::Internet.ip_v4_address to include all IP ranges
  lib/faker/default/internet.rb
  test/faker/default/test_faker_internet.rb
Labels: Bug/Fixes

#1497 add TV Shows to table of contents
  unreleased_README.md
Labels: Documentation

#1499 Adds some items on pt-BR locales seniority and education levels. And removes duplicated items from cities list.
  lib/locales/pt-BR.yml
Labels: Update locales

#1496 Update yaml format in docs
  CONTRIBUTING.md
  README.md
  lib/locales/README.md
  tasks/reformat_yaml.rake
  unreleased_README.md
Labels: Chores

#1501 fix asajj_ventress alternate name
  lib/locales/en/star_wars.yml
Labels: Update locales

#1502 Add support for Armenian language
  lib/locales/arm.yml
  test/test_arm_locale.rb
Labels: Update locales
