Repository faker-ruby/faker, pull requests merged in 2018-10, with the labels that each got.

#1381 Add Faker::Games::HalfLife
  README.md
  doc/half_life.md
  lib/faker.rb
  lib/faker/games.rb
  lib/faker/games/half_life.rb
  lib/locales/en/half_life.yml
  test/test_determinism.rb
  test/test_half_life.rb
Labels: Feature Request

#1386 Add a locale file for Arabic language and test it
  lib/locales/ar.yml
  test/test_ar_locale.rb
Labels: Update locales

#1384 Quick number method bugfix
  CHANGELOG.md
  doc/number.md
  lib/faker/number.rb
Labels: Bug/Fixes

#1382 Adding Faker::IDNumber.brazilian_citizen_number
  doc/id_number.md
  lib/faker/id_number.rb
  test/test_faker_id_number.rb
Labels: Feature Request

#1062 Markdown exclude method
  CHANGELOG.md
  doc/markdown.md
  lib/faker/markdown.rb
  test/test_faker_markdown.rb
  test/test_faker_national_health_service.rb
Labels: Feature Request

#1390 Add more Dutch names
  lib/locales/nl.yml
Labels: Update locales

#1391 Add state abbr for Sergipe and Tocantins
  lib/locales/pt-BR.yml
Labels: Update locales

#1392 Add missing locales/methods for Faker::Name [pt-BR]
  lib/locales/pt-BR.yml
Labels: Update locales

#1393 Add missing pt-BR methods and locale tests
  CHANGELOG.md
  lib/locales/pt-BR.yml
  test/test_pt_br_locale.rb
Labels: Update locales

#1394 Add name_with_middle - es locale and missing tests
  lib/locales/es.yml
  test/test_es_locale.rb
Labels: Update locales

#1397 style: Organize document format to ja locale
  lib/locales/ja.yml
Labels: Chores

#1398 Fix female_first_name and male_first_name
  CHANGELOG.md
  lib/faker/name.rb
  lib/locales/bg.yml
  lib/locales/en-MS.yml
  lib/locales/fi-FI.yml
  lib/locales/nb-NO.yml
  lib/locales/sk.yml
  lib/locales/sv.yml
  test/test_bg_locale.rb
  test/test_en_ms_locale.rb
  test/test_fi_locale.rb
  test/test_nb_no_locale.rb
  test/test_no-NO_locale.rb
  test/test_sk_locale.rb
  test/test_sv_locale.rb
Labels: Update locales

#1399 Add Faker::HeroesOfTheStorm
  README.md
  doc/heroes_of_the_storm.md
  lib/faker.rb
  lib/faker/games/heroes_of_the_storm.rb
  lib/locales/en/heroes_of_the_storm.yml
  test/test_faker_games_heroes_of_the_storm.rb
Labels: Feature Request

#1389 Load faker I18n using custom backend chaining
  CHANGELOG.md
  lib/faker.rb
  lib/helpers/i18n_backend.rb
  test/test_faker_i18n_backend.rb
Labels: Bug/Fixes

#1396 Add Faker::Creature::Animal
  CHANGELOG.md
  README.md
  doc/animal.md
  lib/faker.rb
  lib/faker/creature.rb
  lib/faker/creature/animal.rb
  lib/locales/en/animal.yml
  test/test_determinism.rb
  test/test_faker_animal.rb
Labels: Feature Request

#1400 Add Faker::Movies::Ghostbusters
  CHANGELOG.md
  README.md
  doc/ghostbusters.md
  lib/faker.rb
  lib/faker/movies.rb
  lib/faker/movies/ghostbusters.rb
  lib/locales/en/ghostbusters.yml
  test/test_determinism.rb
  test/test_faker_movies_ghostbusters.rb
Labels: Feature Request

#1401 Faker::GratefulDead => Faker::Movies::GratefulDead
  CHANGELOG.md
  README.md
  doc/grateful_dead.md
  lib/faker/grateful_dead.rb
  test/test_faker_grateful_dead.rb
Labels: Chores

#1403 Faker::SouthPark => Faker::Movies::SouthPark
  CHANGELOG.md
  README.md
  doc/south_park.md
  lib/faker/south_park.rb
  test/test_faker_south_park.rb
Labels: Chores

#1402 Update heroes_of_the_storm.yml
  CHANGELOG.md
  lib/locales/en/heroes_of_the_storm.yml
Labels: Update locales

#1409 Add DC Comics titles
  doc/dc_comics.md
  lib/faker/dc_comics.rb
  lib/locales/en/dc_comics.yml
  test/test_faker_dc_comics.rb
Labels: Feature Request

#1411 Add several missing locales
  CHANGELOG.md
  lib/locales/da-DK.yml
  lib/locales/en-IND.yml
  lib/locales/en-NZ.yml
  lib/locales/it.yml
  test/test_ar_locale.rb
  test/test_bg_locale.rb
  test/test_ca_cat_locale.rb
  test/test_ca_locale.rb
  test/test_da_dk_locale.rb
  test/test_de_at_locale.rb
  test/test_de_ch_locale.rb
  test/test_de_locale.rb
  test/test_ee_locale.rb
  test/test_en_au_locale.rb
  test/test_en_au_ocker_locale.rb
  test/test_en_ca_locale.rb
  test/test_en_gb_locale.rb
  test/test_en_ind_locale.rb
  test/test_en_ms_locale.rb
  test/test_en_nep_locale.rb
  test/test_en_ng_locale.rb
  test/test_en_nz_locale.rb
  test/test_en_pak_locale.rb
  test/test_en_sg_locale.rb
  test/test_en_ug_locale.rb
  test/test_en_us_locale.rb
  test/test_en_za_locale.rb
  test/test_es_locale.rb
  test/test_es_mx_locale.rb
  test/test_faker_name.rb
  test/test_fi_locale.rb
  test/test_fr_ca_locale.rb
  test/test_fr_ch_locale.rb
  test/test_fr_locale.rb
  test/test_he_locale.rb
  test/test_id_locale.rb
  test/test_it_locale.rb
  test/test_ja_locale.rb
  test/test_ko_locale.rb
  test/test_nb_no_locale.rb
  test/test_nl_locale.rb
  test/test_no_no_locale.rb
  test/test_pl_locale.rb
  test/test_pt_br_locale.rb
  test/test_pt_locale.rb
  test/test_ru_locale.rb
  test/test_sk_locale.rb
  test/test_sv_locale.rb
  test/test_tr_locale.rb
  test/test_uk_locale.rb
  test/test_vi_locale.rb
  test/test_zh_cn_locale.rb
  test/test_zh_tw_locale.rb
Labels: Chores

#1415 Add new Overwatch items
  lib/locales/en/overwatch.yml
Labels: Update locales

#1414 Fixing spelling mistake in Docs for Vehicle
  doc/vehicle.md
Labels: Documentation

#1413 Add Faker::Games::Heroes
  README.md
  doc/heroes.md
  lib/faker/games/heroes.rb
  lib/locales/en/heroes.yml
  test/test_faker_heroes.rb
Labels: Feature Request

#1419 Add deprecate instructions to CONTRIBUTING.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: Documentation

#1410 Add Faker::Vehicle.singapore_license_plate
  doc/vehicle.md
  lib/faker/vehicle.rb
  lib/locales/en-SG.yml
  test/test_en_sg_locale.rb
Labels: Feature Request

#1243 Add image file method to placeholdit
  doc/placeholdit.md
  lib/faker/placeholdit.rb
Labels: Documentation

#1425 NHS: fix occasional bad numbers
  lib/faker/nhs.rb
  test/test_faker_national_health_service.rb
Labels: Bug/Fixes

#1428 Add Faker::Games::SonicTheHedgehog.game
  CHANGELOG.md
  doc/sonic_the_hedgehog.md
  lib/faker/games/sonic_the_hedgehog.rb
  lib/locales/en/sonic_the_hedgehog.yml
  test/test_faker_sonic_the_hedgehog.rb
Labels: Feature Request

#1427 Add Faker::Games::SuperSmashBros
  CHANGELOG.md
  README.md
  doc/super_smash_bros.md
  lib/faker/games/super_smash_bros.rb
  lib/locales/en/super_smash_bros.yml
  test/test_faker_super_smash_bros.rb
Labels: Feature Request

#1429 Remove duplicate key(name) in lib/locales/pl.yml
  lib/locales/pl.yml
Labels: Chores

#1426 Add Faker::PhoneNumber.country_code
  CHANGELOG.md
  doc/phone_number.md
  lib/faker/phone_number.rb
  lib/locales/en/phone_number.yml
  test/test_faker_phone_number.rb
Labels: Feature Request

#1436 Fix regex and add magic string to pass rubocop check
  test/test_faker_phone_number.rb
Labels: Bug/Fixes

#1438 Add Faker::Football.position
  doc/football.md
  lib/faker/football.rb
  lib/locales/en/football.yml
  test/test_faker_football.rb
Labels: Feature Request

#1441 Add Faker::Job pt-BR locales
  CHANGELOG.md
  lib/locales/pt-BR.yml
  test/test_pt_br_locale.rb
Labels: Update locales

#1446 fix: Remove deplicate column 'color' from ja.yml
  lib/locales/ja.yml
Labels: Update locales

#1447 Add Maroon 5 and Paramore to music
  lib/locales/en/music.yml
Labels: Update locales

#1440 Add Faker::Subscription
  CHANGELOG.md
  README.md
  doc/unreleased/subscription.md
  lib/faker/subscription.rb
  lib/locales/en/subscription.yml
  lib/locales/es-MX.yml
  lib/locales/es.yml
  lib/locales/it.yml
  test/test_es_locale.rb
  test/test_es_mx_locale.rb
  test/test_faker_subscription.rb
  test/test_it_locale.rb
  unreleased_CONTENT.md
Labels: Feature Request

#1443 Add new array of cities from brazil
  lib/locales/pt-BR.yml
  test/test_pt_br_locale.rb
Labels: Update locales

#1433 Add Faker::DrivingLicence
  doc/unreleased/driving_licence.md
  lib/faker/driving_licence.rb
  test/test_faker_driving_licence.rb
  unreleased_CONTENT.md
Labels: Feature Request

#1451 Add first name 'Simão' and title prefix to 'Eng.'
  lib/locales/pt.yml
Labels: Update locales

#1450 Update device list and serial codes
  lib/locales/en/device.yml
Labels: Update locales

#1453 Add description to Rubocop cops
  .rubocop.yml
Labels: Documentation

#1456 Faker::Internet.slug excludes "." by default
  lib/faker/internet.rb
Labels: Bug/Fixes

#1457 Add tests for new Faker::Internet.slug glue
  test/test_faker_internet.rb
Labels: Chores
