Repository faker-ruby/faker, pull requests merged in 2018-09, with the labels that each got.

#1352 Add Japanese Food Sushi for Japanese and English
  lib/locales/en/food.yml
  lib/locales/ja.yml
  test/test_faker_food.rb
  test/test_ja_locale.rb
Labels: Update locales

#1353 Update documentation for Faker::Number
  doc/number.md
Labels: Update locales

#1354 Update docs for Lorem
  doc/lorem.md
Labels: Documentation

#1335 Fix Company.luhn_algorithm and add missing tests.
  lib/faker/company.rb
  test/test_faker_company.rb
Labels: Bug/Fixes

#1357 Fix South Africa documentation
  doc/company.md
  doc/finance.md
  doc/south_africa.md
Labels: Documentation

#1358 Add cat breed for Japanese
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Update locales

#1360 Update Food documentation
  doc/food.md
Labels: Documentation

#1362 Faker::Types minor cleanup
  doc/types.md
  lib/faker/types.rb
Labels: Chores

#1364 Fix typo in Faker::Code documentation
  doc/code.md
Labels: Documentation

#1365 Add Faker::Number.within
  CHANGELOG.md
  doc/number.md
  lib/faker/number.rb
  test/test_faker_number.rb
Labels: Feature Request

#1366 Add Faker::Seinfeld.business
  CHANGELOG.md
  doc/seinfeld.md
  lib/faker/seinfeld.rb
  lib/locales/en/seinfeld.yml
  test/test_faker_seinfeld.rb
Labels: Feature Request

#1359 Add Faker::Tezos
  CHANGELOG.md
  README.md
  doc/tezos.md
  lib/faker.rb
  lib/faker/bitcoin.rb
  lib/faker/tezos.rb
  lib/helpers/base58.rb
  test/test_determinism.rb
  test/test_faker_tezos.rb
Labels: Feature Request

#1367 Remove duplicate entry
  lib/locales/en/most_interesting_man_in_the_world.yml
Labels: Update locales

#1368 Don't force enforce_available_locales
  lib/faker.rb
  test/test_helper.rb
Labels: Bug/Fixes

#1156 Add Faker::Json
  .rubocop.yml
  doc/json.md
  lib/faker/json.rb
  test/test_faker_json.rb
Labels: Feature Request

#1355 Fix global clear of unique values for Faker::UniqueGenerator
  CHANGELOG.md
  lib/helpers/unique_generator.rb
  test/test_faker_unique_generator.rb
Labels: Bug/Fixes

#1370 Add missed comma
  lib/locales/ru.yml
Labels: Update locales

#1302 Add Faker::Alphanumeric
  README.md
  doc/alphanumeric.md
  lib/faker.rb
  lib/faker/alphanumeric.rb
  lib/faker/hipster.rb
  lib/faker/lorem.rb
  lib/faker/lovecraft.rb
  lib/faker/types.rb
  test/test_alphanum.rb
Labels: Feature Request

#1372 Add space planet and galaxy for Japanese
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Update locales

#1373 📝 Correct some minor spelling errors
  lib/locales/en/bojack_horseman.yml
Labels: Update locales

#1374 Add Faker::Beer.brand
  doc/beer.md
  lib/locales/en/beer.yml
  test/test_faker_beer.rb
Labels: Feature Request

#1380 Update year in License.txt
  License.txt
Labels: Documentation
