Repository faker-ruby/faker, pull requests merged in 2018-06, with the labels that each got.

#1260 Add Faker::Auto features to Faker::Vehicle
  doc/vehicle.md
  lib/faker/vehicle.rb
  lib/locales/en/vehicle.yml
  test/test_faker_vehicle.rb
Labels: Feature Request

#1121 Better docs for Faker::Food.description
  lib/faker/food.rb
Labels: Documentation

#1141 Add Faker::Coffee.intensifier
  CHANGELOG.md
  doc/coffee.md
  lib/faker/coffee.rb
Labels: Feature Request, Waiting for author's response

#1101 Add Faker::Company.czech_organisation_number
  CHANGELOG.md
  doc/company.md
  lib/faker/company.rb
  test/test_faker_company.rb
Labels: Feature Request

#1266 Add Faker::Science.element_symbol
  CHANGELOG.md
  doc/science.md
  lib/faker/science.rb
  lib/locales/en/science.yml
  test/test_faker_science.rb
Labels: Feature Request

#1269 Update Faker::ProgrammingLanguage.name locales
  CHANGELOG.md
  lib/locales/en/programming_language.yml
Labels: Update locales

#1272 Add Faker::DrWho.actor
  CHANGELOG.md
  doc/dr_who.md
  lib/faker/dr_who.rb
  lib/locales/en/dr_who.yml
  test/test_faker_dr_who.rb
Labels: Feature Request

#1273 Add Faker::Device
  CHANGELOG.md
  README.md
  doc/device.md
  lib/faker/device.rb
  lib/locales/en/device.yml
  test/test_determinism.rb
  test/test_faker_device.rb
Labels: Feature Request

#1275 Fix typo; RedWine should be two words
  lib/locales/en/food.yml
Labels: Update locales

#1268 Add Faker::Nation.national_sport
  CHANGELOG.md
  doc/nation.md
  lib/faker/nation.rb
  lib/locales/en/team.yml
  test/test_faker_nation.rb
Labels: Feature Request

#1262 Add fr_CA locale
  lib/locales/fr-CA.yml
  test/test_fr_ca_locale.rb
Labels: Update locales, Waiting for author's response

#1261 Add fr_CH locale
  CHANGELOG.md
  lib/locales/fr-CH.yml
  test/test_fr_ch_locale.rb
Labels: Update locales, Waiting for author's response

#877 Add Canada SIN generator in Faker::Code
  CHANGELOG.md
  doc/code.md
  lib/faker/code.rb
  test/test_faker_code.rb
Labels: Feature Request

#1264 Prepare Faker::Name.job_titles and Faker::Name.title for deprecation
  CHANGELOG.md
  Gemfile
  doc/name.md
  lib/faker/name.rb
  lib/locales/en/job.yml
  lib/locales/en/name.yml
Labels: Deprecation, Update locales

#817 Faker::Lorem.multibyte for multibyte chars
  doc/lorem.md
  lib/faker/lorem.rb
  lib/locales/en.yml
  test/test_faker_lorem.rb
  test/test_faker_markdown.rb
Labels: Feature Request

#719 Random words to add should be 0
  CHANGELOG.md
  lib/faker/lorem.rb
Labels: Suggestion, Waiting for author's response

#1050 Add Faker::Invoice to generate valid bank slip references
  CHANGELOG.md
  doc/invoice.md
  lib/faker/invoice.rb
  lib/locales/ee.yml
  lib/locales/en/invoice.yml
  lib/locales/fi-FI.yml
  lib/locales/no.yml
  test/test_ee_locale.rb
  test/test_fi_locale.rb
  test/test_invoice.rb
  test/test_no-NO_locale.rb
Labels: Feature Request

#799 Add Faker::ElectricalComponents
  CHANGELOG.md
  README.md
  doc/electrical_components.md
  lib/faker/electrical_components.rb
  lib/locales/en/electrical_components.yml
  test/test_faker_electrical_components.rb
Labels: Feature Request

#1103 Fix inconsistent capitalization in dishes, ingredients and spices, and some other small issues under 'food'
  lib/locales/en/food.yml
Labels: Update locales

#1279 Add Faker::HarryPotter.spell
  CHANGELOG.md
  doc/harry_potter.md
  lib/faker/harry_potter.rb
  lib/locales/en/harry_potter.yml
  test/test_faker_harry_potter.rb
Labels: Feature Request

#1281 Some competitions were in the coaches array
  CHANGELOG.md
  lib/locales/en/football.yml
Labels: Update locales

#1283 Add Faker::Military
  CHANGELOG.md
  README.md
  doc/military.md
  lib/faker/military.rb
  lib/locales/en/military.yml
  test/test_faker_military.rb
Labels: Feature Request

#616 add german commerce translations
  lib/locales/de.yml
Labels: Update locales, Waiting for author's response

#1288 rake console changes - description and contributing.md
  CHANGELOG.md
  CONTRIBUTING.md
  Rakefile
Labels: Feature Request

#1287 Prepare Faker::Time.between deprecation
  CHANGELOG.md
  doc/time.md
  lib/faker/time.rb
Labels: Deprecation

#1133 Fix I18n 0.9.3 compatibility
  Gemfile.lock
  test/test_faker_city.rb
  test/test_faker_commerce.rb
  test/test_faker_street.rb
  test/test_faker_zip_code.rb
  test/test_flexible.rb
Labels: Bug/Fixes

#1274 Allow Faker::Address.zip_code to have leading zero
  .gitignore
  CHANGELOG.md
  lib/faker.rb
  lib/faker/address.rb
  test/test_faker_zip_code.rb
Labels: Bug/Fixes

#1292 Fix flexible keys crash
  CHANGELOG.md
  lib/faker.rb
  test/test_flexible.rb
Labels: Bug/Fixes

#551 Add gender to name generator
  CHANGELOG.md
  doc/name.md
  lib/faker/name.rb
  lib/locales/en/name.yml
  lib/locales/es.yml
  test/test_faker_city.rb
  test/test_faker_name.rb
Labels: Feature Request, Waiting for author's response

#1297 Faker::WorldCup updates
  CHANGELOG.md
  doc/world_cup.md
  lib/faker/world_cup.rb
  lib/locales/en/world_cup.yml
  test/test_faker_world_cup.rb
Labels: Update locales
