Repository faker-ruby/faker, pull requests merged in 2018-08, with the labels that each got.

#1324 Add Faker::SouthAfrica
  CHANGELOG.md
  README.md
  doc/id_number.md
  doc/south_africa.md
  lib/faker/id_number.rb
  lib/faker/south_africa.rb
  lib/locales/ee.yml
  lib/locales/en-ZA.yml
  test/test_ee_locale.rb
  test/test_faker_id_number.rb
  test/test_faker_south_africa.rb
Labels: Feature Request

#1327 fixed 2 quotes
  lib/locales/en/world_of_warcraft.yml
Labels: Update locales

#1332 Fix typo in buffy.big_bads
  lib/locales/en/buffy.yml
Labels: Update locales

#1130 Faker::Vehicle API updates
  CHANGELOG.md
  doc/vehicle.md
  lib/faker/vehicle.rb
  lib/locales/en/vehicle.yml
  lib/locales/pt-BR.yml
  test/test_faker_vehicle.rb
Labels: Feature Request

#1317 Change Faker::Lorem.multibyte logic
  CHANGELOG.md
  lib/faker/lorem.rb
  lib/locales/en.yml
  lib/locales/en/lorem.yml
  test/test_faker_lorem.rb
Labels: Bug/Fixes

#1337 Add the @flexible_key value to the Food Class
  lib/faker/food.rb
  test/test_faker_food.rb
Labels: Feature Request

#1338 Add new translations to the en-ZA locale
  CHANGELOG.md
  lib/locales/en-ZA.yml
  test/test_en_za_locale.rb
Labels: Feature Request

#803 Modify Faker::Educator, Fix #576
  doc/educator.md
  lib/faker/educator.rb
  lib/locales/en/educator.yml
  test/test_faker_educator.rb
Labels: Feature Request

#1340 Fix typos and additions for Faker::Esport
  lib/locales/en/esport.yml
Labels: Update locales

#1342 Added Faker::CryptoCoin scope
  README.md
  doc/crypto_coin.md
  lib/faker/crypto_coin.rb
  lib/locales/en/crypto_coin.yml
  test/test_faker_crypto_coin.rb
Labels: Feature Request

#1343 Update cell phone format to be phonelib compatible for Vietnam locale
  lib/locales/vi.yml
Labels: Update locales

#1334 Faker::Number.leading_zero_number should always start with 0
  CHANGELOG.md
  lib/faker/number.rb
  test/test_faker_number.rb
Labels: Bug/Fixes

#1347 Remove launchy dependency
  CHANGELOG.md
  CONTRIBUTING.md
  Gemfile.lock
  Rakefile
  faker.gemspec
Labels: Chores

#1348 Add Faker::Finance.vat_number
  CHANGELOG.md
  doc/finance.md
  lib/faker/finance.rb
  lib/locales/en/finance.yml
  test/test_faker_finance.rb
  test/test_helper.rb
Labels: Feature Request

#1350 Faker::CryptoCoin minor changes
  doc/crypto_coin.md
  lib/faker/crypto_coin.rb
  lib/locales/en/crypto_coin.yml
  test/test_faker_crypto_coin.rb
Labels: Documentation, Update locales
