Repository faker-ruby/faker, pull requests merged in 2018-11, with the labels that each got.

#1458 Update Faker::DragonBall.characters locales
  lib/locales/en/dragon_ball.yml
Labels: Update locales

#1461 Add Orphea to heroes of the storm locale file.
  lib/locales/en/heroes_of_the_storm.yml
Labels: Update locales

#1460 Add Faker::Marketing
  doc/unreleased/marketing.md
  lib/faker/marketing.rb
  lib/locales/en/marketing.yml
  test/test_faker_marketing.rb
  unreleased_CONTENT.md
Labels: Feature Request

#1462 Fix documentation on Faker::Avatar
  doc/v1.9.1/avatar.md
Labels: Update locales

#1468 Update "Black Pink" to "Blackpink"
  lib/locales/en/kpop.yml
Labels: Update locales

#1430 Adding Faker::Company.brazilian_company_number
  doc/unreleased/company.md
  lib/faker/company.rb
  test/test_faker_company.rb
Labels: Feature Request

#1470 remove duplicate generators from the default list
  unreleased_README.md
Labels: Documentation

#1471 Add music and movies namespace
  CHANGELOG.md
  doc/unreleased/default/back_to_the_future.md
  doc/unreleased/default/hobbit.md
  doc/unreleased/default/lebowski.md
  doc/unreleased/default/lord_of_the_rings.md
  doc/unreleased/default/princess_bride.md
  doc/unreleased/default/star_wars.md
  doc/unreleased/default/umphreys_mcgee.md
  doc/unreleased/default/v_for_vendetta.md
  doc/unreleased/movies/back_to_the_future.md
  doc/unreleased/movies/hobbit.md
  doc/unreleased/movies/lebowski.md
  doc/unreleased/movies/lord_of_the_rings.md
  doc/unreleased/movies/movie.md
  doc/unreleased/movies/princess_bride.md
  doc/unreleased/movies/star_wars.md
  doc/unreleased/movies/v_for_vendetta.md
  doc/unreleased/music/umphreys_mcgee.md
  lib/faker/default/back_to_the_future.rb
  lib/faker/default/lebowski.rb
  lib/faker/default/lord_of_the_rings.rb
  lib/faker/default/princess_bride.rb
  lib/faker/default/star_wars.rb
  lib/faker/default/umphreys_mcgee.rb
  lib/faker/default/v_for_vendetta.rb
  lib/faker/deprecate/back_to_the_future.rb
  lib/faker/deprecate/lebowski.rb
  lib/faker/deprecate/lord_of_the_rings.rb
  lib/faker/deprecate/princess_bride.rb
  lib/faker/deprecate/star_wars.rb
  lib/faker/deprecate/umphreys_mcgee.rb
  lib/faker/deprecate/v_for_vendetta.rb
  lib/faker/movies/back_to_the_future.rb
  lib/faker/movies/lebowski.rb
  lib/faker/movies/lord_of_the_rings.rb
  lib/faker/movies/movie.rb
  lib/faker/movies/princess_bride.rb
  lib/faker/movies/star_wars.rb
  lib/faker/movies/v_for_vendetta.rb
  lib/faker/music/umphreys_mcgee.rb
  test/deprecate/test_deprecate_back_to_the_future.rb
  test/deprecate/test_deprecate_lebowski.rb
  test/deprecate/test_deprecate_lord_of_the_rings.rb
  test/deprecate/test_deprecate_princess_bride.rb
  test/deprecate/test_deprecate_star_wars.rb
  test/deprecate/test_deprecate_umphreys_mcgee.rb
  test/deprecate/test_deprecate_v_for_vendetta.rb
  test/faker/movies/test_faker_back_to_the_future.rb
  test/faker/movies/test_faker_lebowski.rb
  test/faker/movies/test_faker_lord_of_the_rings.rb
  test/faker/movies/test_faker_princess_bride.rb
  test/faker/movies/test_faker_star_wars.rb
  test/faker/movies/test_faker_v_for_vendetta.rb
  test/faker/music/test_faker_umphreys_mcgee.rb
  unreleased_README.md
Labels: Deprecation

#1478 Fixed documentation for Faker::Internet.password
  doc/v1.9.1/internet.md
Labels: Documentation

#1475 Adds Faker::Nation.flag
  doc/unreleased/default/nation.md
  doc/v1.9.1/nation.md
  lib/faker/default/nation.rb
  lib/locales/en/nation.yml
  test/faker/default/test_faker_nation.rb
Labels: Feature Request

#1481 Add Blockchain namespace
  doc/unreleased/blockchain/bitcoin.md
  doc/unreleased/blockchain/ethereum.md
  doc/unreleased/blockchain/tezos.md
  lib/faker/blockchain/bitcoin.rb
  lib/faker/blockchain/ethereum.rb
  lib/faker/blockchain/tezos.rb
  lib/faker/default/bitcoin.rb
  lib/faker/default/ethereum.rb
  lib/faker/default/tezos.rb
  lib/faker/deprecate/bitcoin.rb
  lib/faker/deprecate/ethereum.rb
  lib/faker/deprecate/tezos.rb
  test/deprecate/test_deprecate_bitcoin.rb
  test/deprecate/test_deprecate_ethereum.rb
  test/deprecate/test_deprecate_tezos.rb
  test/faker/blockchain/bitcoin.rb
  test/faker/blockchain/ethereum.rb
  test/faker/blockchain/tezos.rb
  unreleased_README.md
Labels: Deprecation

#1480 Add Music, Movies and TvShows namespaces
  doc/unreleased/movies/harry_potter.md
  doc/unreleased/movies/hitchhikers_guide_to_the_galaxy.md
  doc/unreleased/music/rock_band.md
  doc/unreleased/tv_shows/michael_scott.md
  doc/unreleased/tv_shows/rupaul.md
  lib/faker/default/harry_potter.rb
  lib/faker/default/hitchhikers_guide_to_the_galaxy.rb
  lib/faker/default/michael_scott.rb
  lib/faker/default/rupaul.rb
  lib/faker/deprecate/harry_potter.rb
  lib/faker/deprecate/hitchhikers_guide_to_the_galaxy.rb
  lib/faker/deprecate/michael_scott.rb
  lib/faker/deprecate/rock_band.rb
  lib/faker/deprecate/ru_paul.rb
  lib/faker/movies/harry_potter.rb
  lib/faker/movies/hitchhikers_guide_to_the_galaxy.rb
  lib/faker/music/rock_band.rb
  lib/faker/tv_shows/michael_scott.rb
  lib/faker/tv_shows/ru_paul.rb
  test/deprecate/test_deprecate_harry_potter.rb
  test/deprecate/test_deprecate_hitchhikers_guide_to_the_galaxy.rb
  test/deprecate/test_deprecate_michael_scott.rb
  test/deprecate/test_deprecate_rock_band.rb
  test/deprecate/test_deprecate_ru_paul.rb
  test/faker/movies/test_faker_harry_potter.rb
  test/faker/movies/test_faker_hitchhikers_guide_to_the_galaxy.rb
  test/faker/music/test_faker_rock_band.rb
  test/faker/tv_shows/test_michael_scott.rb
  test/faker/tv_shows/test_ru_paul.rb
  unreleased_README.md
Labels: Deprecation

#1484 ZELDAs games are translated to japanese
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Update locales

#1474 Fr format and translation
  lib/locales/en/currency.yml
  lib/locales/fr.yml
  test/test_fr_locale.rb
Labels: Update locales

#1486 Added some professions in company.yml.
  lib/locales/en/company.yml
Labels: Update locales
