Repository faker-ruby/faker, pull requests merged in 2019-11, with the labels that each got.

#1824 Added Canadian Country Code
  lib/locales/en-CA.yml
  test/test_en_ca_locale.rb
Labels: Update locales

#1819 Adding chilean_id in Faker::IDNumber
  doc/default/id_number.md
  lib/faker/default/id_number.rb
  test/faker/default/test_faker_id_number.rb
Labels: Feature Request

#1825 Bump version to 2.7.0
  CHANGELOG.md
Labels: Documentation, Needs review

#1810 Add yard docs for Faker::Coffee methods
  lib/faker/default/coffee.rb
Labels: Documentation

#1799 Cleanup world_cup YARD docs
  lib/faker/default/world_cup.rb
Labels: Documentation

#1793 add Faker::Relationship YARD docs
  lib/faker/default/relationship.rb
Labels: Documentation

#1808 Adds domain option for Internet email and domain_name methods
  doc/default/internet.md
  lib/faker/default/internet.rb
  test/faker/default/test_faker_internet.rb
Labels: Feature Request

#1833 Explain safe_email method
  doc/default/internet.md
Labels: Documentation

#1803 add YARD doc for Faker::Coin
  lib/faker/default/coin.rb
Labels: Documentation

#1835 Remove duplicate method description
  doc/default/commerce.md
Labels: Documentation

#1563 Fix generating Faker::Bank#routing_number
  lib/faker/default/bank.rb
  test/faker/default/test_faker_bank.rb
Labels: Bug/Fixes

#1841 Fix strange result from `Lorem.word` in ja locale
  lib/locales/ja.yml
Labels: Update locales
