Repository faker-ruby/faker, pull requests merged in 2019-08, with the labels that each got.

#1683 Rollback Faker::Time changes
  doc/default/time.md
  lib/locales/en.yml
Labels: Bug/Fixes

#1685 Upgrade i18n
  Gemfile.lock
  faker.gemspec
Labels: Bug/Fixes

#1495 Add Brazilian documents generation and documentation
  doc/default/id_number.md
  lib/faker/default/id_number.rb
  test/faker/default/test_faker_id_number.rb
Labels: Feature Request

#1686 Update test-unit gem to 3.3.3
  Gemfile.lock
  faker.gemspec
Labels: Feature Request

#1703 Return HTTPS URLs from Lorem Flickr
  doc/default/lorem_flickr.md
  lib/faker/default/lorem_flickr.rb
  test/faker/default/test_faker_lorem_flickr.rb
Labels: Documentation

#1698 Add warn for positional arguments when using Faker 2.0
  lib/faker.rb
  lib/faker/books/dune.rb
  lib/faker/books/lovecraft.rb
  lib/faker/default/address.rb
  lib/faker/default/alphanumeric.rb
  lib/faker/default/app.rb
  lib/faker/default/avatar.rb
  lib/faker/default/bank.rb
  lib/faker/default/boolean.rb
  lib/faker/default/chile_rut.rb
  lib/faker/default/code.rb
  lib/faker/default/commerce.rb
  lib/faker/default/company.rb
  lib/faker/default/crypto_coin.rb
  lib/faker/default/date.rb
  lib/faker/default/demographic.rb
  lib/faker/default/driving_licence.rb
  lib/faker/default/file.rb
  lib/faker/default/fillmurray.rb
  lib/faker/default/finance.rb
  lib/faker/default/hipster.rb
  lib/faker/default/id_number.rb
  lib/faker/default/internet.rb
  lib/faker/default/invoice.rb
  lib/faker/default/json.rb
  lib/faker/default/lorem.rb
  lib/faker/default/lorem_flickr.rb
  lib/faker/default/lorem_pixel.rb
  lib/faker/default/markdown.rb
  lib/faker/default/measurement.rb
  lib/faker/default/name.rb
  lib/faker/default/nhs.rb
  lib/faker/default/number.rb
  lib/faker/default/omniauth.rb
  lib/faker/default/phone_number.rb
  lib/faker/default/placeholdit.rb
  lib/faker/default/relationship.rb
  lib/faker/default/source.rb
  lib/faker/default/string.rb
  lib/faker/default/stripe.rb
  lib/faker/default/time.rb
  lib/faker/default/twitter.rb
  lib/faker/default/types.rb
  lib/faker/default/vehicle.rb
  lib/faker/default/world_cup.rb
  lib/faker/games/dota.rb
  lib/faker/movies/star_wars.rb
  test/faker/default/test_faker_measurement.rb
Labels: Deprecation

#1715 Fix changelog versions
  CHANGELOG.md
Labels: Documentation

#1716 Bump version to 2.2.1
  CHANGELOG.md
  Gemfile.lock
  lib/faker/version.rb
Labels: Documentation
