Repository faker-ruby/faker, pull requests merged in 2019-10, with the labels that each got.

#1778 Upgrade rubocop to 0.75.0
  .rubocop.yml
  Gemfile.lock
  faker.gemspec
  lib/faker/default/driving_licence.rb
Labels: dependencies

#1789 Faker::WorldCup YARD docs
  lib/faker/default/world_cup.rb
Labels: Documentation

#1755 Add Faker::Date.in_date_period
  doc/default/date.md
  lib/faker/default/date.rb
  test/faker/default/test_faker_date.rb
Labels: Feature Request

#1806 Add Terry Bogard to Super Smash Bros. options
  lib/locales/en/super_smash_bros.yml
Labels: Update locales

#1813 Translate Canadian provinces for fr-CA
  lib/locales/fr-CA.yml
Labels: Update locales

#1814 Add Discord link
  README.md
Labels: Documentation

#1816 Add Japanese bank names
  lib/locales/ja.yml
Labels: Update locales

#1817 Add Japanese animal names
  lib/locales/ja.yml
Labels: Update locales

#1289 Add SemVer compatibility badge to README
  README.md
Labels: Suggestion
