Repository faker-ruby/faker, pull requests merged in 2019-01, with the labels that each got.

#1493 Add Faker::Books::CultureSeries
  doc/unreleased/books/culture_series.md
  lib/faker/books/culture_series.rb
  lib/locales/en/culture_series.yml
  test/faker/books/test_faker_culture_series.rb
  test/test_determinism.rb
  unreleased_README.md
Labels: Feature Request

#1503 Deprecate ::Dune and ::Lovecraft
  CHANGELOG.md
  doc/unreleased/books/book.md
  doc/unreleased/books/dune.md
  doc/unreleased/books/lovecraft.md
  doc/unreleased/default/dune.md
  doc/unreleased/default/lovecraft.md
  lib/faker/books/book.rb
  lib/faker/books/culture_series.rb
  lib/faker/books/dune.rb
  lib/faker/books/lovecraft.rb
  lib/faker/default/dune.rb
  lib/faker/default/lovecraft.rb
  lib/faker/deprecate/dune.rb
  lib/faker/deprecate/lovecraft.rb
  test/deprecate/test_deprecate_dune.rb
  test/deprecate/test_deprecate_lovecraft.rb
  test/faker/books/test_book.rb
  test/faker/books/test_dune.rb
  test/faker/books/test_lovecraft.rb
  unreleased_README.md
Labels: Deprecation

#1509 Fix Faker::Address.country_by_code
  lib/locales/en/address.yml
  test/faker/default/test_country_code.rb
Labels: Update locales

#1512 Fix numerical part of Dutch postcode
  lib/locales/nl.yml
  test/test_nl_locale.rb
Labels: Bug/Fixes

#1514 Distinguish between 'brand' and 'name'
  CHANGELOG.md
  lib/locales/en/beer.yml
Labels: Update locales
