Repository faker-ruby/faker, pull requests merged in 2019-09, with the labels that each got.

#1721 Update rubocop
  Gemfile.lock
  faker.gemspec
  lib/faker/blockchain/tezos.rb
  lib/faker/default/alphanumeric.rb
  lib/faker/default/id_number.rb
  lib/faker/default/omniauth.rb
  lib/faker/default/twitter.rb
  lib/faker/default/vehicle.rb
  lib/faker/movies/star_wars.rb
  tasks/reformat_yaml.rake
  test/faker/default/test_faker_crypto_coin.rb
  test/faker/default/test_faker_vehicle.rb
  test/test_determinism.rb
  test/test_locale.rb
Labels: dependencies

#1722 Fix examples in the Dota docs
  doc/games/dota.md
Labels: Documentation

#1717 Fix ambiguity in element_symbol field
  lib/locales/en/science.yml
Labels: Update locales

#1724 Include rubocop-faker autocorrect in deprecation
  lib/faker.rb
  lib/faker/books/dune.rb
  lib/faker/books/lovecraft.rb
  lib/faker/default/address.rb
  lib/faker/default/alphanumeric.rb
  lib/faker/default/app.rb
  lib/faker/default/avatar.rb
  lib/faker/default/bank.rb
  lib/faker/default/boolean.rb
  lib/faker/default/chile_rut.rb
  lib/faker/default/code.rb
  lib/faker/default/commerce.rb
  lib/faker/default/company.rb
  lib/faker/default/crypto_coin.rb
  lib/faker/default/date.rb
  lib/faker/default/demographic.rb
  lib/faker/default/driving_licence.rb
  lib/faker/default/file.rb
  lib/faker/default/fillmurray.rb
  lib/faker/default/finance.rb
  lib/faker/default/hipster.rb
  lib/faker/default/id_number.rb
  lib/faker/default/internet.rb
  lib/faker/default/invoice.rb
  lib/faker/default/json.rb
  lib/faker/default/lorem.rb
  lib/faker/default/lorem_flickr.rb
  lib/faker/default/lorem_pixel.rb
  lib/faker/default/markdown.rb
  lib/faker/default/measurement.rb
  lib/faker/default/name.rb
  lib/faker/default/nhs.rb
  lib/faker/default/number.rb
  lib/faker/default/omniauth.rb
  lib/faker/default/phone_number.rb
  lib/faker/default/placeholdit.rb
  lib/faker/default/relationship.rb
  lib/faker/default/source.rb
  lib/faker/default/string.rb
  lib/faker/default/stripe.rb
  lib/faker/default/time.rb
  lib/faker/default/twitter.rb
  lib/faker/default/types.rb
  lib/faker/default/vehicle.rb
  lib/faker/default/world_cup.rb
  lib/faker/games/dota.rb
  lib/faker/movies/star_wars.rb
Labels: Feature Request

#1728 Bump version to 2.2.2
  CHANGELOG.md
  Gemfile.lock
  lib/faker/version.rb
Labels: Documentation

#1723 Add pokemon name in Johto area
  lib/locales/ja.yml
Labels: Update locales

#1732 Quebec province postal codes starts by [GHJ], adding missing two
  lib/locales/en-CA.yml
Labels: Update locales

#1738 Add mock data for Apple OAuth
  doc/default/omniauth.md
  lib/faker/default/omniauth.rb
  test/faker/default/test_faker_omniauth.rb
Labels: Feature Request

#1553 Yard powered docs
  .gitignore
  .yardopts
  CONTRIBUTING.md
  Gemfile.lock
  Rakefile
  faker.gemspec
  lib/faker/blockchain/bitcoin.rb
  lib/faker/blockchain/ethereum.rb
  lib/faker/blockchain/tezos.rb
  lib/faker/books/book.rb
  lib/faker/books/culture_series.rb
  lib/faker/books/dune.rb
  lib/faker/books/lovecraft.rb
  lib/faker/creature/animal.rb
  lib/faker/creature/cat.rb
  lib/faker/creature/dog.rb
  lib/faker/creature/horse.rb
  lib/faker/default/alphanumeric.rb
  lib/faker/default/app.rb
  lib/faker/default/artist.rb
  lib/faker/default/avatar.rb
  lib/faker/default/boolean.rb
  lib/faker/default/gender.rb
  lib/faker/default/hacker.rb
  lib/faker/default/house.rb
  lib/faker/default/internet.rb
  lib/faker/default/lorem.rb
  lib/faker/default/programming_language.rb
  lib/faker/default/source.rb
  lib/faker/games/elder_scrolls.rb
  lib/faker/games/fallout.rb
  lib/faker/games/game.rb
  lib/faker/games/half_life.rb
  lib/faker/games/overwatch.rb
  lib/faker/games/super_smash_bros.rb
  lib/faker/games/zelda.rb
  lib/faker/tv_shows/breaking_bad.rb
Labels: Feature Request

#1741 Fix .gitignore for YARD.
  .gitignore
Labels: Documentation

#1739 Bump version to 2.3.0
  CHANGELOG.md
  Gemfile.lock
  lib/faker/version.rb
Labels: Documentation

#1743 Fix another ambiguity in element_symbol field
  lib/locales/en/science.yml
Labels: Update locales

#1748 fix typo from bread to breed
  lib/locales/ja.yml
Labels: Update locales

#1740 Add more YARD docs
  README.md
  lib/faker/default/appliance.rb
  lib/faker/default/dessert.rb
  lib/faker/default/device.rb
  lib/faker/default/electrical_components.rb
  lib/faker/default/greek_philosophers.rb
  lib/faker/default/industry_segments.rb
  lib/faker/default/marketing.rb
  lib/faker/default/military.rb
  lib/faker/default/nato_phonetic_alphabet.rb
  lib/faker/default/science.rb
  lib/faker/default/subscription.rb
  lib/faker/default/superhero.rb
  lib/faker/games/dota.rb
  lib/faker/games/heroes.rb
  lib/faker/games/heroes_of_the_storm.rb
  lib/faker/games/league_of_legends.rb
  lib/faker/games/myst.rb
  lib/faker/games/pokemon.rb
  lib/faker/games/sonic_the_hedgehog.rb
  lib/faker/games/witcher.rb
  lib/faker/games/world_of_warcraft.rb
  lib/faker/japanese_media/dragon_ball.rb
  lib/faker/japanese_media/sword_art_online.rb
  lib/faker/movies/hobbit.rb
  lib/faker/movies/movie.rb
  lib/faker/music/grateful_dead.rb
  lib/faker/music/phish.rb
  lib/faker/music/rock_band.rb
Labels: Documentation

#1752 fix creature i18n path in japanese
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Update locales

#1742 Add Faker::Blockchain::Aeternity
  README.md
  doc/blockchain/aeternity.md
  lib/faker/blockchain/aeternity.rb
  test/faker/blockchain/aeternity.rb
Labels: Feature Request

#1754 Bump version to 2.4.0
  CHANGELOG.md
  Gemfile.lock
  lib/faker/version.rb
Labels: Documentation

#1756 Add more miscellaneous YARD docs
  lib/faker/default/nation.rb
  lib/faker/japanese_media/one_piece.rb
  lib/faker/movies/back_to_the_future.rb
  lib/faker/movies/ghostbusters.rb
  lib/faker/movies/harry_potter.rb
  lib/faker/movies/hitchhikers_guide_to_the_galaxy.rb
  lib/faker/movies/lebowski.rb
  lib/faker/movies/lord_of_the_rings.rb
  lib/faker/movies/princess_bride.rb
  lib/faker/movies/star_wars.rb
  lib/faker/movies/v_for_vendetta.rb
Labels: Documentation

#1758 Add YARD docs for Doctor Who and fix a method name.
  doc/tv_shows/dr_who.md
  lib/faker/tv_shows/dr_who.rb
  lib/locales/en/dr_who.yml
  test/faker/tv_shows/test_dr_who.rb
Labels: Documentation

#1753 Add YARD docs for Date, Time, and Number
  lib/faker/default/date.rb
  lib/faker/default/number.rb
  lib/faker/default/time.rb
Labels: Documentation

#1759 Add YARD docs for all remaining TV Shows
  lib/faker/music/umphreys_mcgee.rb
  lib/faker/tv_shows/aqua_teen_hunger_force.rb
  lib/faker/tv_shows/bojack_horseman.rb
  lib/faker/tv_shows/buffy.rb
  lib/faker/tv_shows/community.rb
  lib/faker/tv_shows/dumb_and_dumber.rb
  lib/faker/tv_shows/family_guy.rb
  lib/faker/tv_shows/friends.rb
  lib/faker/tv_shows/game_of_thrones.rb
  lib/faker/tv_shows/hey_arnold.rb
  lib/faker/tv_shows/how_i_met_your_mother.rb
  lib/faker/tv_shows/michael_scott.rb
  lib/faker/tv_shows/new_girl.rb
  lib/faker/tv_shows/parks_and_rec.rb
  lib/faker/tv_shows/rick_and_morty.rb
  lib/faker/tv_shows/ru_paul.rb
  lib/faker/tv_shows/seinfeld.rb
  lib/faker/tv_shows/silicon_valley.rb
  lib/faker/tv_shows/simpsons.rb
  lib/faker/tv_shows/south_park.rb
  lib/faker/tv_shows/star_trek.rb
  lib/faker/tv_shows/stargate.rb
  lib/faker/tv_shows/stranger_things.rb
  lib/faker/tv_shows/the_expanse.rb
  lib/faker/tv_shows/the_fresh_prince_of_bel_air.rb
  lib/faker/tv_shows/the_it_crowd.rb
  lib/faker/tv_shows/the_thick_of_it.rb
  lib/faker/tv_shows/twin_peaks.rb
  lib/faker/tv_shows/venture_bros.rb
Labels: Documentation

#1751 fix from Color.name to Color.color_name
  test/test_ar_locale.rb
  test/test_ca_locale.rb
  test/test_de_locale.rb
  test/test_es_locale.rb
  test/test_ja_locale.rb
Labels: Bug/Fixes

#1764 Remove "mint green" from list of colors
  lib/locales/en/color.yml
Labels: Update locales

#1767 Fix two incorrect flexible method calls.
  lib/faker/default/chuck_norris.rb
  lib/faker/games/zelda.rb
Labels: Bug/Fixes

#1771 Fix some rubocop comments that were showing up in YARD docs.
  lib/faker/default/app.rb
  lib/faker/default/avatar.rb
  lib/faker/default/internet.rb
Labels: Documentation

#1773 Two new locales added: th and en-TH
  lib/locales/en-TH.yml
  lib/locales/th.yml
  test/test_en_th_locale.rb
  test/test_th_locale.rb
Labels: Feature Request, Update locales
