Repository faker-ruby/faker, pull requests merged in 2019-02, with the labels that each got.

#1523 Updated Avatar docs for v1.9.2 and unreleased.
  doc/unreleased/default/avatar.md
  doc/v1.9.2/default/avatar.md
Labels: Documentation

#1522 Updated the internet faker docs for v1.9.2 and unreleased.
  doc/unreleased/default/internet.md
  doc/v1.9.2/default/internet.md
Labels: Documentation

#1526 test: Add missing test and sort word
  test/test_ja_locale.rb
Labels: Chores

#1525 Add gender binary type for Japanese
  lib/locales/ja.yml
  test/test_ja_locale.rb
Labels: Update locales

#1528 add heavy_equipment, roles, trades, standard_cost_codes to construction
  lib/faker/default/construction.rb
  lib/locales/en/construction.yml
  test/faker/default/test_faker_construction.rb
Labels: Feature Request

#1530 Change Armenian Locale
  lib/locales/hy.yml
  test/test_hy_locale.rb
Labels: Update locales

#1535 Rollback #1389
  lib/faker.rb
  lib/helpers/i18n_backend.rb
  test/faker/default/test_faker_i18n_backend.rb
Labels: Bug/Fixes

#1537 Adds the Faker::Sports::Basketball Generator
  doc/sports/basketball.md
  lib/faker/sports/basketball.rb
  lib/locales/en/basketball.yml
  test/faker/sports/test_faker_basketball.rb
  test/test_determinism.rb
Labels: Feature Request

#1520 Allow subdomains for Internet.domain_name
  CHANGELOG.md
  doc/default/internet.md
  lib/faker/default/internet.rb
  test/faker/default/test_faker_internet.rb
Labels: Feature Request

#1540 Add sic_code to company #355
  doc/unreleased/default/company.md
  lib/faker/default/company.rb
  lib/locales/en/company.yml
  test/faker/default/test_faker_company.rb
Labels: Feature Request

#1542 Fixed typos to the unreleased_README.md
  README.md
  unreleased_README.md
Labels: Chores

#1543 Add pt-BR genders
  lib/locales/pt-BR.yml
  test/test_pt_br_locale.rb
Labels: Update locales

#1549 Faker::Movies::GratefulDead => Faker::Music::GratefulDead
  doc/unreleased/music/grateful_dead.md
  lib/faker/deprecate/unreleased/movies/grateful_dead.rb
  lib/faker/music/grateful_dead.rb
  lib/locales/en/grateful_dead.yml
  test/deprecate/unreleased/test_deprecate_faker_grateful_dead.rb
  test/faker/music/test_faker_grateful_dead.rb
  unreleased_README.md
Labels: Deprecation

#1554 Extend list of cryptocurrencies
  doc/default/crypto_coin.md
  lib/locales/en/crypto_coin.yml
  test/faker/default/test_faker_crypto_coin.rb
Labels: Update locales
