Repository faker-ruby/faker, pull requests merged in 2019-07, with the labels that each got.

#1649 Remove mexicoMX
  lib/locales/en/address.yml
Labels: Update locales

#1653 Add /faker-ruby/faker-bot to README
  README.md
Labels: Documentation

#1660 Update FillMurray Links To Include www
  doc/default/fillmurray.md
  lib/faker/default/fillmurray.rb
  lib/faker/default/number.rb
  test/faker/default/test_faker_fillmurray.rb
Labels: v2

#1417 Rework Faker::Time::between
  doc/default/time.md
  lib/faker/default/time.rb
  test/faker/default/test_faker_time.rb
Labels: Feature Request

#1634 Corrected other occurrences of spelling vehicle spelling error, deprecated Space launch_vehicule
  doc/default/space.md
  lib/faker/default/space.rb
  lib/locales/en/space.yml
  test/faker/default/test_faker_space.rb
Labels: Deprecation

#1675 Fix off-by-one error when formatting month names
  lib/locales/en.yml
Labels: Bug/Fixes
