Repository faker-ruby/faker, pull requests merged in 2019-06, with the labels that each got.

#1631 Faker::Tezos: add block faker
  doc/unreleased/blockchain/tezos.md
  lib/faker/blockchain/tezos.rb
  test/faker/blockchain/tezos.rb
Labels: Feature Request

#1640 Add pull_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: Documentation

#1516 Deprecate Faker::Number.decimal_part and .leading_zero_number
  lib/faker/default/number.rb
Labels: Deprecation

#1361 Add Faker::File.dir
  doc/default/file.md
  doc/unreleased/default/file.md
  lib/faker/default/file.rb
  test/faker/default/test_faker_file.rb
Labels: Feature Request
