Repository faker-ruby/faker, pull requests merged in 2019-12, with the labels that each got.

#1844 Add yard doc alpha method fix in contribution file
  CONTRIBUTING.md
Labels: Documentation

#1766 Add YARD docs for Faker::Address
  lib/faker/default/address.rb
Labels: Documentation

#1802 add YARD doc for Faker::Food
  lib/faker/default/food.rb
Labels: Documentation

#1772 Refactor Faker::Educator and add docs
  lib/faker/default/educator.rb
  lib/locales/en/educator.yml
Labels: Documentation, Refactoring

#1769 Add more YARD docs
  lib/faker/default/ancient.rb
  lib/faker/default/chuck_norris.rb
  lib/faker/default/color.rb
  lib/faker/default/currency.rb
  lib/faker/default/esport.rb
  lib/faker/default/fillmurray.rb
  lib/faker/default/space.rb
  lib/faker/default/team.rb
Labels: Documentation

#1849 Add YARD docs for Faker::BossaNova.
  lib/faker/default/bossa_nova.rb
Labels: Documentation

#1851 Add YARD docs for Faker::Crypto.
  lib/faker/default/crypto.rb
Labels: Documentation

#1847 Makes minor refactors on Internet.domain_name method
  lib/faker/default/internet.rb
  test/faker/default/test_faker_internet.rb
Labels: Refactoring

#1820 Add pt-BR for science, space and electrical_components generators
  lib/locales/pt-BR.yml
Labels: Update locales

#1790 add Faker::Beer YARD docs
  lib/faker/default/beer.rb
Labels: Documentation

#1797 add YARD doc for Faker::Job
  lib/faker/default/job.rb
Labels: Documentation

#1859 Fixed YYYY-DD-MM dates in CHANGELOG
  CHANGELOG.md
Labels: Documentation

#1860 Fix Educator methods returning bad data.
  lib/locales/en/educator.yml
Labels: Update locales

#1864 adding `male` & `female` first names for persian
  lib/locales/fa.yml
Labels: Update locales

#1863 Add Faker::Gender.short_binary_type
  doc/default/gender.md
  lib/faker/default/gender.rb
  lib/locales/en/gender.yml
  test/faker/default/test_faker_gender.rb
Labels: Feature Request

#1568 Add Faker::Address.mail_box and some NZ locale updates
  README.md
  doc/default/address.md
  lib/faker/default/address.rb
  lib/faker/default/bank.rb
  lib/locales/en-NZ.yml
  lib/locales/en/address.yml
  test/faker/default/test_faker_address.rb
Labels: Feature Request, Update locales

#1862 Update phone number documentation
  doc/default/phone_number.md
  lib/locales/en/phone_number.yml
Labels: Documentation

#1874 Extract constants in Faker::Music
  lib/faker/music/music.rb
Labels: Refactoring

#1877 Fix the path names for bg.yml
  lib/locales/bg.yml
Labels: Update locales

#1868 Fix a deprecation warning in unique_generator.rb related to the kwargs change in Ruby 2.7.
  lib/helpers/unique_generator.rb
Labels: Bug/Fixes

#1878 Fix name related fields in ca locale
  lib/locales/ca.yml
Labels: Chores

#1879 Field changes in da-DK locale
  lib/locales/da-DK.yml
Labels: Update locales
