Repository faker-ruby/faker, pull requests merged in 2020-05, with the labels that each got.

#1973 Fix mis-quotations
  lib/locales/en/heroes_of_the_storm.yml
  lib/locales/en/house.yml
Labels: Update locales

#1982 Add YARD docs to Faker::Cosmere
  lib/faker/default/cosmere.rb
Labels: Documentation

#1980 Add YARD docs for Faker::Construction
  lib/faker/default/construction.rb
Labels: Documentation

#1981 Add YARD docs to Faker::Stripe
  lib/faker/default/stripe.rb
Labels: Documentation

#1948 Add Faker::Computer
  lib/faker/default/computer.rb
  lib/locales/en/computer.yml
  test/faker/default/test_faker_computer.rb
  test/test_helper.rb
Labels: Feature Request

#1959 add YARD docs to Faker::University
  .rubocop.yml
  lib/faker/default/university.rb
Labels: Documentation

#1956 add YARD docs to Faker::SlackEmoji
  lib/faker/default/slack_emoji.rb
Labels: Documentation

#1985 Fix an error for `Faker::Computer.os`
  lib/faker/default/computer.rb
Labels: Bug/Fixes

#1983 Add YARD docs to Faker::Twitter
  lib/faker/default/twitter.rb
Labels: Documentation

#1485 Plays and musicals
  doc/unreleased/music/show.md
  lib/faker/music/show.rb
  lib/locales/en/show.yml
  test/faker/music/test_faker_show.rb
  unreleased_README.md
Labels: Feature Request

#1966 ADD Faker::Games:DnD
  doc/games/dnd.md
  lib/faker/games/dnd.rb
  lib/locales/en/dnd.yml
  test/faker/games/test_dnd.rb
Labels: Feature Request

#1943 Update documentation for unique.exclude
  README.md
  test/faker/default/test_faker_lorem.rb
Labels: Documentation

#1960 Added Faker::Blood
  lib/faker.rb
  lib/faker/default/blood.rb
  lib/locales/en/blood.yml
  test/faker/default/test_faker_blood.rb
Labels: Feature Request

#1993 Add YARD docs for Faker::Vehicle
  lib/faker/default/vehicle.rb
Labels: Documentation

#1964 en-AU locale updates
  lib/faker/default/bank.rb
  lib/faker/default/vehicle.rb
  lib/locales/en-AU.yml
  test/faker/default/test_faker_bank.rb
  test/faker/default/test_faker_vehicle.rb
  test/test_en_au_locale.rb
  test/test_pt_br_locale.rb
Labels: Feature Request

#1962 adding Pearl Jam to the Music module
  doc/music/pearl_jam.md
  lib/faker/music/pearl_jam.rb
  lib/locales/en/pearl_jam.yml
  test/faker/music/test_faker_pearl_jam.rb
Labels: Feature Request

#2001 Add YARD docs to Faker::South_Africa
  lib/faker/default/south_africa.rb
Labels: Documentation

#2010 add missing links in README.md
  README.md
Labels: Documentation

#2004 Add YARD docs to Faker::String
  lib/faker/default/string.rb
Labels: Documentation

#1931 Add Faker::Movies::Departed Class
  README.md
  doc/movies/departed.md
  lib/faker/movies/departed.rb
  lib/locales/en/departed.yml
  test/faker/movies/test_faker_departed.rb
Labels: Feature Request

#2022 Add YARD docs to Faker::Invoice
  lib/faker/default/invoice.rb
Labels: Documentation

#2021 Add YARD docs to Faker::Hipster
  lib/faker/default/hipster.rb
Labels: Documentation

#2020 Add YARD docs to Faker::Measurement
  lib/faker/default/measurement.rb
Labels: Documentation

#2027 Bump version to 2.12.0
  CHANGELOG.md
Labels: Documentation

#1952 Add Faker::Movie.title
  doc/movies/movie.md
  lib/faker/movies/movie.rb
  lib/locales/en/movie.yml
  test/faker/movies/test_faker_movie.rb
Labels: Feature Request

#2028 Reorganize some tests
  test/faker/books/test_dune.rb
  test/faker/books/test_faker_dune.rb
  test/faker/default/test_faker_movie.rb
  test/faker/games/test_faker_control.rb
  test/faker/games/test_faker_dnd.rb
  test/faker/games/test_faker_dota.rb
  test/faker/games/test_faker_elder_scrolls.rb
  test/faker/games/test_faker_fallout.rb
  test/faker/games/test_faker_game.rb
  test/faker/games/test_faker_heroes.rb
  test/faker/games/test_faker_heroes_of_the_storm.rb
  test/faker/games/test_faker_league_of_legends.rb
  test/faker/games/test_faker_myst.rb
  test/faker/games/test_faker_overwatch.rb
  test/faker/games/test_faker_pokemon.rb
  test/faker/games/test_faker_sonic_the_hedgehog.rb
  test/faker/games/test_faker_super_smash_bros.rb
  test/faker/games/test_faker_warhammer_fantasy.rb
  test/faker/games/test_faker_witcher.rb
  test/faker/games/test_faker_world_of_warcraft.rb
  test/faker/games/test_faker_zelda.rb
  test/faker/movies/test_faker_movie.rb
Labels: Bug/Fixes, Chores
