Repository faker-ruby/faker, pull requests merged in 2020-11, with the labels that each got.

#2183 Add state_abbr for id locale
  lib/locales/id.yml
  test/test_id_locale.rb
Labels: Update locales

#2203 Rollback PR #2169 and bump 2.15.1
  CHANGELOG.md
  Gemfile.lock
  lib/faker.rb
  lib/faker/version.rb
  test/test_locale.rb
Labels: Bug/Fixes

#2201 Typo in Lebowski Quote
  lib/locales/en/lebowski.yml
Labels: Update locales

#2205 Faker::Mountain doc
  README.md
  doc/default/mountain.md
Labels: Documentation

#2208 Feat/add blockchain tezos keys
  doc/blockchain/tezos.md
  lib/faker/blockchain/tezos.rb
  test/faker/blockchain/test_tezos.rb
Labels: Feature Request
