Repository faker-ruby/faker, pull requests merged in 2020-06, with the labels that each got.

#2029 Allow passing a string to specific Faker::Date methods.
  lib/faker/default/date.rb
Labels: Documentation

#2030 Add general documentation for Faker::Blood
  doc/default/blood.md
Labels: Documentation

#2033 Use Faker::Base::ULetters constant instead
  lib/faker/default/company.rb
  test/faker/default/test_faker_company.rb
Labels: Chores

#2031 Deprecate `HeroesOfTheStorm.class`
  doc/games/heroes_of_the_storm.md
  lib/faker/games/heroes_of_the_storm.rb
  lib/locales/en/heroes_of_the_storm.yml
  test/faker/games/test_faker_heroes_of_the_storm.rb
Labels: Deprecation

#2037 Bug Fix: BIC Collission (Issue 1907)
  lib/locales/en/bank.yml
  test/faker/default/test_faker_bank.rb
Labels: Bug/Fixes

#1670 Adds Faker::Music::Prince
  README.md
  doc/music/prince.md
  lib/faker/music/prince.rb
  lib/locales/en/prince.yml
  test/faker/music/test_faker_prince.rb
Labels: Feature Request

#2041 Reduce Lines in char.rb
  lib/helpers/char.rb
Labels: Bug/Fixes

#1932 Added AHTF Wisdom
  doc/tv_shows/aqua_teen_hunger_force.md
  lib/faker/tv_shows/aqua_teen_hunger_force.rb
  lib/locales/en/aqua_teen_hunger_force.yml
  test/faker/tv_shows/test_aqua_teen_hunger_force.rb
Labels: Feature Request

#2035 Add YARD docs to Faker::ID_Number
  doc/default/id_number.md
  lib/faker/default/id_number.rb
Labels: Documentation

#2036 Add YARD docs to Faker::Markdown
  doc/default/markdown.md
  lib/faker/default/markdown.rb
Labels: Documentation

#2052 Add YARD docs to Faker::Lorem_Pixel
  lib/faker/default/lorem_pixel.rb
Labels: Documentation

#2053 Add YARD docs to Faker::Lorem_Flickr
  lib/faker/default/lorem_flickr.rb
Labels: Documentation

#1821 Add HTTP status codes generator
  doc/internet/http.md
  lib/faker/default/internet_http.rb
  test/faker/default/test_faker_internet_http.rb
Labels: Feature Request

#2061 Update docs for Faker::Date with separate examples
  doc/default/date.md
  lib/faker/default/date.rb
Labels: Documentation

#2068 Bump version to 2.13.0
  CHANGELOG.md
  Gemfile.lock
  lib/faker/default/address.rb
  lib/faker/default/bank.rb
  lib/faker/default/blood.rb
  lib/faker/default/date.rb
  lib/faker/default/gender.rb
  lib/faker/default/internet_http.rb
  lib/faker/default/name.rb
  lib/faker/default/world_cup.rb
  lib/faker/games/control.rb
  lib/faker/games/dnd.rb
  lib/faker/games/heroes_of_the_storm.rb
  lib/faker/games/minecraft.rb
  lib/faker/games/warhammer_fantasy.rb
  lib/faker/movies/departed.rb
  lib/faker/movies/movie.rb
  lib/faker/music/pearl_jam.rb
  lib/faker/music/phish.rb
  lib/faker/music/prince.rb
  lib/faker/music/rush.rb
  lib/faker/music/show.rb
  lib/faker/tv_shows/aqua_teen_hunger_force.rb
  lib/faker/tv_shows/big_bang_theory.rb
  lib/faker/tv_shows/dr_who.rb
  lib/faker/tv_shows/futurama.rb
  lib/faker/tv_shows/simpsons.rb
  lib/faker/tv_shows/suits.rb
  lib/faker/version.rb
Labels: Documentation
