Repository faker-ruby/faker, pull requests merged in 2022-10, with the labels that each got.

#2579 Add note about Random behavior on MiniTest
  README.md
Labels: 📘 Documentation

#2580 Remove mentions to `master` and use `main`
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  faker.gemspec
Labels: 📘 Documentation

#2582 Add `clojure` as a language option to `Faker::Source` generator
  lib/locales/en/source.yml
Labels: ⏲️ PR: In Queue for Review, hacktoberfest-accepted

#2584 Automate workflow to publish to RubyGems.
  .github/workflows/publish.yml
Labels: ⭐ PR: Feature, hacktoberfest-accepted

#2591 Fixes iban checksum calculation
  lib/faker/default/bank.rb
  test/faker/default/test_faker_bank.rb
Labels: ⏲️ PR: In Queue for Review, 🐞 PR: Bugfix, 🙏🏽 PR: Needs Further Updates
