Repository faker-ruby/faker, pull requests merged in 2022-08, with the labels that each got.

#2511 Danish id number
  doc/default/id_number.md
  lib/faker/default/id_number.rb
  test/faker/default/test_faker_id_number.rb
Labels: ⏲️ PR: In Queue for Review, ⭐ PR: Feature

#2367 Add generator for vulnerability identifiers
  README.md
  doc/default/vulnerability_identifier.md
  lib/faker/default/vulnerability_identifier.rb
  test/faker/default/test_faker_vulnerability_identifier.rb
Labels: ⏲️ PR: In Queue for Review, ⭐ PR: Feature

#2518 Add the ability to generate a mime type of a specific media type
  CONTRIBUTING.md
  doc/default/file.md
  lib/faker/default/file.rb
  lib/locales/en/file.yml
  test/faker/default/test_faker_file.rb
Labels: ⚒️ Improvement, 🙏🏽 PR: Needs Further Updates

#2455 Add IDNumber.french_insee_number
  doc/default/id_number.md
  lib/faker/default/id_number.rb
  test/faker/default/test_faker_id_number.rb
Labels: 🏃🏽 PR: In Progress, ↩ Needs Revisiting, ⭐ PR: Feature

#2530 fix flaky user agent test
  test/faker/default/test_faker_internet.rb
Labels: Chores

#2531 Update GitHub Issues and Pull Request Templates [ci-skip]
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chores, ⚒️ Improvement

#2520 Thread safety
  lib/faker.rb
  lib/helpers/unique_generator.rb
  test/faker/default/test_faker_unique_generator.rb
  test/test_determinism.rb
Labels: ⏲️ PR: In Queue for Review, ⭐ PR: Feature, ⚒️ Improvement

#2535 Fix warning instance variable uninitialized
  lib/faker.rb
  test/faker/default/test_faker_food.rb
  test/faker/default/test_faker_hobby.rb
  test/faker/default/test_faker_vehicle.rb
Labels: 🏃🏽 PR: In Progress, 🙏🏽 PR: Needs Tests, 🐞 PR: Bugfix

#2491 fix italy VAT and add italy condominium fiscal code generator
  lib/faker/default/finance.rb
  lib/locales/en/finance.yml
Labels: 🏃🏽 PR: In Progress, 🐞 PR: Bugfix, 🙏🏽 PR: Needs Further Updates

#2460 Add ChileRut.full_formatted_rut
  doc/default/chile_rut.md
  lib/faker/default/chile_rut.rb
  test/faker/default/test_faker_chile_rut.rb
Labels: ⭐ PR: Feature

#2538 Drop support for EOL Ruby versions (`2.5` and `2.6`)
  .github/workflows/ruby.yml
  .rubocop.yml
  faker.gemspec
  lib/faker/default/bank.rb
  lib/faker/default/code.rb
  test/faker/default/test_faker_birthday_in_leap_year.rb
  test/faker/default/test_faker_id_number.rb
Labels: 🏃🏽 PR: In Progress, Deprecation
