Repository faker-ruby/faker, pull requests merged in 2022-09, with the labels that each got.

#2557 Use rubocop-rake to lint Rake tasks
  .rubocop.yml
  Gemfile.lock
  faker.gemspec
Labels: ⚒️ Improvement

#2544 Update simplecov gem
  .github/workflows/ruby.yml
  Gemfile.lock
  faker.gemspec
  test/test_helper.rb
Labels: ⏲️ PR: In Queue for Review, ⚒️ Improvement

#2551 security: set explicit and strict token-permissions on GitHub workflows
  .github/workflows/ruby.yml
Labels: ⏲️ PR: In Queue for Review, 👮 Security

#2558 Remove unneeded require in lib/faker.rb
  lib/faker.rb
Labels: 🏃🏽 PR: In Progress, Chores, ⚒️ Improvement, 🙏🏽 PR: Needs Further Updates

#2566 Issue-2464: Add color luminosity options
  lib/faker/default/color.rb
  test/faker/default/test_faker_color.rb
Labels: ⏲️ PR: In Queue for Review, ⭐ PR: Feature
