Repository faker-ruby/faker, pull requests merged in 2022-11, with the labels that each got.

#2601 added travel folder and airports
  README.md
  doc/travel/airport.md
  lib/faker/travel/airport.rb
  lib/locales/en/airport.yml
  test/faker/travel/test_faker_airports.rb
Labels: ⏲️ PR: In Queue for Review, 🙏🏽 PR: Needs Documentation, ⭐ PR: Feature

#2619 Spongebob TV show collections
  README.md
  doc/tv_shows/spongebob.md
  lib/faker/tv_shows/spongebob.rb
  lib/locales/en/spongebob.yml
  test/faker/tv_shows/spongebob.rb
Labels: 🏃🏽 PR: In Progress, ⭐ PR: Feature

#2533 fix: ensure generated passwords have correct characters when mix_case & special_characters enabled
  doc/default/internet.md
  lib/faker/default/internet.rb
  test/faker/default/test_faker_internet.rb
Labels: 🏃🏽 PR: In Progress, 🐞 PR: Bugfix

#2630 Update README and CONTRIBUTING guides
  CONTRIBUTING.md
  MAINTAINING.md
  README.md
Labels: ⚒️ Improvement
