Repository faker-ruby/faker, pull requests merged in 2023-07, with the labels that each got.

#2750 Added Archer into tv category.
  README.md
  doc/tv_shows/archer.md
  lib/faker/tv_shows/archer.rb
  lib/locales/en/archer.yml
  test/faker/tv_shows/test_archer.rb
Labels: 🏃🏽 PR: In Progress, ⭐ PR: Feature

#2755 Add train station generator
  README.md
  doc/travel/train_station.md
  lib/faker/travel/airport.rb
  lib/faker/travel/train_station.rb
  lib/locales/en/train_station.yml
  test/faker/travel/test_faker_train_station.rb
Labels: 🏃🏽 PR: In Progress

#2710 Introduce PositionalGenerator
  lib/faker.rb
  lib/faker/default/code.rb
  lib/faker/default/company.rb
  lib/faker/default/driving_licence.rb
  lib/faker/default/id_number.rb
  lib/faker/default/vehicle.rb
  lib/helpers/positional_generator.rb
Labels: 🏃🏽 PR: In Progress

#2800 Add prefixes to french name locale (`Faker::Name.name`)
  lib/locales/fr/name.yml
Labels: 🌐 Update Locales, ⚒️ Improvement

#2778 Add `max_rut` option to `Faker::ChileRut.rut`
  lib/faker/default/chile_rut.rb
  test/faker/default/test_faker_chile_rut.rb
Labels: ⚒️ Improvement, 🙏🏽 PR: Needs Further Updates
